Added development env setup instructions in documentation
distributed-system-analysis/sarjitsu pull request #35
Opened 2017-08-08 08:24 UTC by smitthakkar96

2017-08-08 09:38 UTC, arcolife requested changes

2017-08-08 09:38 UTC, arcolife commented on README.md
> +- Install dependencies with ``` sudo dnf install python3-devel && pip install -r requirements.txt ```
fyi, I installed these too:
```
gpgme-devel
gpgme
```

2017-08-08 09:38 UTC, arcolife commented on README.md
> +- Set DEBUG=True in config.py
and the manual changes we did to URLs for frontend, api etc.. linked as container names in config/init.py ?

2017-08-08 09:38 UTC, arcolife commented on README.md
> +- Modify CFG_PATH in config.py to ``` lib/backend/conf/sarjustu.ini.example ```
wouldn't that relative path depend on where we execute `python server.py` from ? more like an indication to user to set this per their env?

2017-08-08 09:38 UTC, arcolife commented on README.md
> +- Install dependencies with ``` sudo dnf install python3-devel && pip install -r requirements.txt ```
and activate virtual env :-)

sorry about nitpicking!

2017-08-08 09:39 UTC, arcolife commented
@smitthakkar96 just added a few notes. Thanks for submitting the PR!

2017-08-08 09:53 UTC, arcolife commented
ref from my env: https://gist.github.com/arcolife/8cceeca6f0a051a6312442a35fd5ad70#gistcomment-2171018

..in addition to https://github.com/distributed-system-analysis/sarjitsu/pull/35#discussion_r131864872

@smitthakkar96 side note, I was unable to convert the sa binary after these changes. so __perhaps__ an additional step needed about paths related to SA binary processing scripts in `backend/src/scripts` ?

2017-08-08 10:38 UTC, smitthakkar96 commented on README.md
> +- Install dependencies with ``` sudo dnf install python3-devel && pip install -r requirements.txt ```
When I did on my fedora machine, I had to run dnf install python3-devel python3-gpgme and it worked.

2017-10-30 20:12 UTC, GeetikaBatra commented
redis linkage in web service's config `__init__.py` could be avoided and instead, a small hack to /etc/hosts can be done through 
```
echo "$(docker inspect $(docker ps | grep redis | awk '{print $NF}') | egrep '\"IPAddress\": \"172' | awk -F'"' '{print $(NF-1)}') redis" | sudo tee -a /etc/hosts
```

2017-11-04 11:35 UTC, arcolife commented
reworked into https://github.com/distributed-system-analysis/sarjitsu/pull/41

2017-11-04 11:35 UTC, closed without merging